USE SPRING;

CREATE TABLE IF NOT EXISTS USER_ACCOUNT(
	USER_ID VARCHAR(20),
    PASSWORD VARCHAR(20),
	USER_NAME VARCHAR(20),
	PHONE INT,
	EMAIL VARCHAR(50),
	PRIMARY KEY (USER_ID)
);

INSERT INTO USER_ACCOUNT(USER_ID, PASSWORD, USER_NAME, PHONE, EMAIL) VALUES ('admin', 'admin', '관리자', 01000000000, 'admin@master.com');
INSERT INTO USER_ACCOUNT(USER_ID, PASSWORD, USER_NAME, PHONE, EMAIL) VALUES ('user01', 'password', '마우스', 01011111111, 'user01@master.com');
INSERT INTO USER_ACCOUNT(USER_ID, PASSWORD, USER_NAME, PHONE, EMAIL) VALUES ('study', 'room', '키보드', 01022222222, '@twoz.net');

CREATE TABLE IF NOT EXISTS BOARD_NOTICE(   
	CONTENT_ID   INT AUTO_INCREMENT,
	WRITER   VARCHAR(15),
	WRITE_TIME   DATETIME,
	TITLE   VARCHAR(50),
	CONTENT   TEXT,
	PRIMARY KEY(CONTENT_ID)
);

INSERT INTO BOARD_NOTICE(WRITER, WRITE_TIME, TITLE, CONTENT) 
VALUES('admin', NOW(), '영업시간 안내', '공휴일 포함  아침 9시 ~ 밤11시 영업합니다.');

CREATE TABLE IF NOT EXISTS BOARD_JOIN(   
	CONTENT_ID   INT auto_increment,
	WRITER   VARCHAR(15),
	WRITE_TIME   DATETIME,
	TITLE   VARCHAR(50),
	CONTENT   TEXT,
	MEMBER_NEED   INT,
	CLICKS   INT,
    PRIMARY KEY(CONTENT_ID)
);

INSERT INTO BOARD_JOIN(WRITER, WRITE_TIME, TITLE, CONTENT, MEMBER_NEED, CLICKS) VALUES('user01', now(), '중국어 스터디원 구합니다.', 'user01@twoz.com으로 연락주세요.', 3, 0);
INSERT INTO BOARD_JOIN(WRITER, WRITE_TIME, TITLE, CONTENT, MEMBER_NEED, CLICKS) VALUES('study', now(), 'IT_프로그래밍 스터디', '프로그래밍 같이 공부하실 분들 연락주세요.', 5, 0);

CREATE TABLE IF NOT EXISTS COMMENT_JOIN(
	COMMENT_ID   INT  AUTO_INCREMENT,
	CONTENT_ID   INT,
	WRITER VARCHAR(15),
	WRITE_TIME   DATETIME,
	CONTENT   TEXT,
	PRIMARY KEY(COMMENT_ID),
	FOREIGN KEY(CONTENT_ID) REFERENCES BOARD_JOIN(CONTENT_ID)
);

INSERT INTO COMMENT_JOIN(CONTENT_ID, WRITER, WRITE_TIME, CONTENT) VALUES(2, 'user01', now(), '연락드렸습니다!');
INSERT INTO COMMENT_JOIN(CONTENT_ID, WRITER, WRITE_TIME, CONTENT) VALUES(2, 'admin', now(), '저도 연락드렸습니다!');


QUIT